# Note: there are many handy hints in comments in this example -- remove them when you've finalized your recipe
# If your package is python based, we recommend using Grayskull to generate it instead:
# https://github.com/conda-incubator/grayskull

# Jinja variables help maintain the recipe as you'll update the version only here.
# Using the name variable with the URL in line 14 is convenient
# when copying and pasting from another recipe, but not really needed.
{% set name = "ucb-bar-riscv-toolchains" %}
{% set version = "1.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: chipyard-src
    git_url: https://github.com/ucb-bar/chipyard.git
    git_rev: {{ version }}

build:
  number: 1
  skip: True # [not linux]

requirements:
  build:
    - gcc=10
    - gxx=10
    - gawk
    - bison=3.4
    - gtk3
    - glib
    - pkg-config
    - bison
    - flex
    - autoconf
    - automake
    - libtool
    - python
    - gmp
    - texinfo
    - patch
    - mpfr
    - mpc
    - python
    - patch
    - texinfo
    - subversion
    - chrpath
    - git
    - wget
    - expat
    - zlib
    - binutils

  host:
    - kernel-headers_linux-64>=2.6.38

  run:
    - python

test:
  commands:
    - ls -alh

about:
  home: https://github.com/simplejson/simplejson
  summary: 'Simple, fast, extensible JSON encoder/decoder for Python'
  description: |
    simplejson is a simple, fast, complete, correct and extensible
    JSON <https://json.org> encoder and decoder for Python 2.5+ and
    Python 3.3+. It is pure Python code with no dependencies, but includes
    an optional C extension for a serious speed boost.
  # Remember to specify the license variants for BSD, Apache, GPL, and LGPL.
  # Use the SPDX identifier, e.g: GPL-2.0-only instead of GNU General Public License version 2.0
  # See https://spdx.org/licenses/
  license: MIT
  # The license_family, i.e. "BSD" if license is "BSD-3-Clause".
  # Optional
  license_family: MIT
  # It is required to include a license file in the package,
  # (even if the license doesn't require it) using the license_file entry.
  # Please also note that some projects have multiple license files which all need to be added using a valid yaml list.
  # See https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#license-file
  license_file: LICENSE.txt
  # The doc_url and dev_url are optional.
  doc_url: https://simplejson.readthedocs.io/
  dev_url: https://github.com/simplejson/simplejson

extra:
  recipe-maintainers:
    - abejgonzalez
