# Note: there are many handy hints in comments in this example -- remove them when you've finalized your recipe
# If your package is python based, we recommend using Grayskull to generate it instead:
# https://github.com/conda-incubator/grayskull

# Jinja variables help maintain the recipe as you'll update the version only here.
# Using the name variable with the URL in line 14 is convenient
# when copying and pasting from another recipe, but not really needed.
{% set name = "ucb-bar-riscv-tools" %}
{% set version = "9.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: src
    git_url: https://github.com/abejgonzalez/ucb-bar-riscv-tools.git
    git_rev: b780fc8c68a7edb6b9823ef4f21fd1d57a911902

build:
  number: 0
  skip: True # [not linux]

requirements:
  build:
    # toolchain deps
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - gawk
    # if building riscv-toolchain from source, we need to use bison=3.4 until we have
    # https://github.com/riscv-collab/riscv-binutils-gdb/commit/314ec7aeeb1b2e68f0d8fb9990f2335f475a6e33
    - bison ==3.4.*
    - patch
    - git
    - make
    - dtc
    - binutils
    - texinfo

    # extra qemu deps
    #- gtk3
    #- glib
    #- pkg-config
    #- flex
    #  #- expat
    #- autoconf
    #- automake
    ## qemu also requires being built against kernel-headers >= 2.6.38 because of it's use of
    ## MADV_NOHUGEPAGE in a call to madvise.  See:
    ## https://man7.org/linux/man-pages/man2/madvise.2.html
    ## https://conda-forge.org/docs/maintainer/knowledge_base.html#using-centos-7
    ## obvi this would need to be made linux-specific if we supported other MacOS or Windows
    #- kernel-headers_linux-64>=2.6.38

    # extra (probably not needed)
    - python ==3.8.*
      #- subversion
      #- chrpath
      #- wget
      #- rsync
      #- psutil
      #- doit
      #- gitpython
      #- humanfriendly
      #- e2fsprogs
      #- ctags
    - libtool
      #- ca-certificates
      #- gengetopt
      #- libffi
      #- libusb1
      #- cmake
      #- expect
      #- sphinx
      #- pygments
      #- sphinx-autobuild
      #- sphinx_rtd_theme
      #- docutils
      #- sbt
      #- verilator==4.034
      #- vim
  host:
    - expat
    - ncurses
    - gmp
    - mpfr
    - mpc
    - zlib

      ## qemu specific host needs
      #host:
      #  - glib
      #  - pixman
      #  - zstd
      #  - zlib
      #  - libcurl

test:
  commands:
    - test "$($PREFIX/riscv/bin/riscv64-unknown-elf-gcc -dumpversion)" = "$PKG_VERSION"

about:
  home: https://github.com/abejgonzalez/ucb-bar-riscv-tools

extra:
  recipe-maintainers:
    - abejgonzalez
